{% set name = "bluesky-queueserver-api" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d7710fc4b39c4921ed0199bd460ded7dca2f32d10baa1148ac700d65a47c1780

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bluesky-queueserver
    - httpx
    - python >=3.7

test:
  imports:
    - bluesky_queueserver_api

about:
  home: https://github.com/bluesky/bluesky-queueserver-api
  summary: Python API for Bluesky Queue Server
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://blueskyproject.io/bluesky-queueserver-api
  dev_url: https://github.com/bluesky/bluesky-queueserver-api

extra:
  recipe-maintainers:
    - dmgav
    - mrakitin
